version: '3'
services:
  web:
    build: # the following 2 lines means that we will choose a different dockerfile than the default
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build: # the following 2 lines means that we will choose a different dockerfile than the default
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]